Auth
h33h/Mars-Rover pull request #4
Opened 2021-11-02 18:43 UTC by h33h

2021-11-02 19:35 UTC, IlyaValevich requested changes

2021-11-02 19:35 UTC, IlyaValevich commented on Mars Rover/Presenters/LoginFormPresenter.swift
> +    // MARK: - LoginFormPresenter: Methods
Follow for the uniformity of the code:
```
extension LoginFormPresenter {

     // MARK: - LoginFormPresenter: Methods
     // Delegate setter method
     func setDelegate(delegate: LoginFormPresenterDelegate) {
         self.delegate = delegate
     }

     // Login function will call some sign In methods from service
     func login() {
     }

}
```

2021-11-02 19:35 UTC, IlyaValevich commented on Mars Rover/ViewControllers/LoginFormViewController.swift
> +    }
Do not spam the code with unnecessary comments

2021-11-02 19:35 UTC, IlyaValevich commented on Mars Rover/ViewControllers/LoginFormViewController.swift
> +}
```
  extension LoginFormViewController: LoginFormPresenterDelegate {

      // MARK: - LoginFormViewController: LoginFormPresenterDelegate Methods
      // if login succeed
      func successfullLogin() {
         // storyboard that contains MainMenuViewController
         let mainMenuStoryboard = UIStoryboard(name: "MainMenu", bundle: nil)
         // instantinate MainMenuViewController from mainMenuStoryboard
         guard let mainMenuVC = mainMenuStoryboard.instantiateViewController(withIdentifier: "MainMenu") as? MainMenuViewController
          else { return }
          setElementsDisabled(value: false)
          // present mainMenuVC
          present(mainMenuVC, animated: true, completion: nil)
      }

      // if login failed
      func failureLogin(error: String) {
          setElementsDisabled(value: false)
      }

  }
  ```

2021-11-02 19:35 UTC, IlyaValevich commented on Mars Rover/ViewControllers/LoginFormViewController.swift
> +    }
```
extension LoginFormViewController: UITextFieldDelegate {

     // MARK: - LoginFormViewController: UITextField Delegate Methods
     func textFieldShouldReturn(_ textField: UITextField) -> Bool {
         // when click on return button, keyboard closes
         textField.resignFirstResponder()
         return true
      }

}
```

2021-11-02 19:35 UTC, IlyaValevich commented on Mars Rover/Views/AuthorizationTextField.swift
> +    /// IBInspectable for realtime update of values in InterfaceBuilder
```// IBInspectable for realtime update of values in InterfaceBuilder```

2021-11-02 19:35 UTC, IlyaValevich commented on Mars Rover/Views/AuthorizationTextField.swift
> +}
```
extension AuthorizationTextField {

    // MARK: - AuthorizationTextField: Override Methods
    override func textRect(forBounds bounds: CGRect) -> CGRect {
        bounds.inset(by: insetsWithMargin)
    }

    override func editingRect(forBounds bounds: CGRect) -> CGRect {
        bounds.inset(by: insetsWithMargin)
    }

 }
```

2021-11-02 19:35 UTC, IlyaValevich commented on Mars Rover/Views/AuthorizationTextField.swift
> +}
```
extension AuthorizationTextField {

      // MARK: - AuthorizationTextField: Methods
      // called from init methods
      private func setupView() {
          // leftSideImageView setup
          let margin: CGFloat = 16
          leftSideImageView.contentMode = .center
          leftSideImageView.frame = CGRect(x: -margin / 2,
                                           y: -margin / 2,
                                           width: bounds.height + margin,
                                           height: bounds.height + margin)
          leftSideImageView.layer.cornerRadius = leftSideImageView.bounds.width / 2
          leftSideImageView.isHidden = isleftSideImageisHidden
          addSubview(leftSideImageView)
      }

 }
```

2021-11-02 19:40 UTC, IlyaValevich requested changes
The user now always gets to the authentication screen, shouldn't there be a switch to the menu for an already authenticated user?

2021-11-02 19:40 UTC, IlyaValevich commented on Mars Rover/Presenters/LoginFormPresenter.swift
> +    func login() {
Don't leave it empty, add // TODO:...

2021-11-03 11:13 UTC, h33h commented
> The user now always gets to the authentication screen, shouldn't there be a switch to the menu for an already authenticated user?

It should be realized as soon as authorization service will be added

2021-11-03 15:05 UTC, IlyaValevich commented on Mars Rover/Presenters/LoginFormPresenter.swift
> +}
Add empty line

2021-11-03 15:05 UTC, IlyaValevich commented on Mars Rover/Presenters/LoginFormPresenter.swift
> +}
Add empty line

2021-11-03 15:05 UTC, IlyaValevich commented on Mars Rover/Views/AuthorizationTextField.swift
> +        leftSideImageView.layer.cornerRadius = leftSideImageView.bounds.width / 2
Use a variable instead of numbers

2021-11-03 15:17 UTC, merged